export enum ActionTypes {
    CREATE_USER = "CREATE_USER",
    FETCH_USER = "FETCH_USER",
    GET_USER = "GET_USER",
    LOGIN_USER = "LOGIN_USER",
    LOGOUT_USER = "LOGOUT_USER",
    USER_REGISTER = "USER_REGISTER",
    COMPLETE_REG_PROGRESS = "COMPLETE_REG_PROGRESS"
}
